Add Prometheus monitoring function
openimsdk/open-im-server pull request #1337
Opened 2023-11-04 09:11 UTC by xuexihuang

<br>

#### 🔍 What type of PR is this?

#### 👀 What this PR does / why we need it:

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

#### 🅰 Which issue(s) this PR fixes:

Fixes #1336 

#### 📝 Special notes for your reviewer:

#### 🎯 Describe how to verify it

#### 📑 Additional documentation e.g., RFC, notion, Google docs, usage docs, etc.:

2023-11-04 10:28 UTC, cubxxw commented
Dear @openimsdk/openim 

I wanted to bring to your attention that there seems to be an issue with the PR launch. I have checked the GitHub actions and it appears to be abnormal. I have attached the status in the comments section below for your reference.

If possible, could you please take a look and assist in resolving the matter? Your expertise in this area would be greatly appreciated.

Thank you for your time and attention to this matter.

Best regards,
cubxxw

[![OpenIM CI Aotu Build and Install](https://github.com/openimsdk/open-im-server/actions/workflows/openimci.yml/badge.svg)](https://github.com/openimsdk/open-im-server/actions/workflows/openimci.yml)

2023-11-04 10:30 UTC, cubxxw requested changes
After careful consideration and evaluation, we have come to the conclusion that the manifest directory is no longer necessary. We have found better solutions for both CI and local development, and believe that removing it will streamline our processes and improve efficiency.

We kindly request that the manifest directory be removed from our systems. We understand that this may require some effort, but we believe it will ultimately benefit our team and our projects.

Thank you for your understanding and cooperation.

2023-11-04 10:30 UTC, cubxxw commented on pkg/common/startrpc/start.go
> +		reg, metric, err = prom_metrics.NewGrpcPromObj(cusMetrics)
```suggestion
		reg, metric, err = prom_metrics.NewGrpcPromObj(cusMetrics)
```
It appears that the errors here have not been handled properly. May I suggest taking a closer look at the code and implementing some improvements to ensure that errors are handled more effectively in the future? One potential solution could be to use a try-catch block to handle any potential errors that may arise.

2023-11-04 10:31 UTC, cubxxw commented
> ## [Codecov](https://app.codecov.io/gh/openimsdk/open-im-server/pull/1337?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=openimsdk) Report
> > Merging [#1337](https://app.codecov.io/gh/openimsdk/open-im-server/pull/1337?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=openimsdk) ([419c97c](https://github.com/openimsdk/open-im-server/commit/419c97cd4a2f48783d1b95eb5082d513dc774241)) into [main](https://app.codecov.io/gh/openimsdk/open-im-server/commit/cb0bf6443545773e7185dd68bf83e1b6ab43694a?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=openimsdk) ([cb0bf64](https://github.com/openimsdk/open-im-server/commit/cb0bf6443545773e7185dd68bf83e1b6ab43694a)) will **not change** coverage.
> > The diff coverage is `n/a`.
> 
> ```diff
> @@          Coverage Diff          @@
> ##            main   #1337   +/-   ##
> =====================================
>   Coverage   2.41%   2.41%           
> =====================================
>   Files         13      13           
>   Lines        786     786           
> =====================================
>   Hits          19      19           
>   Misses       764     764           
>   Partials       3       3           
> ```

@xuexihuang If it is possible, would you kindly consider adding some unit tests to improve code coverage and quality? Thank you for your attention to this matter.

2023-11-06 09:13 UTC, cubxxw submitted a review, later dismissed

2023-11-07 02:28 UTC, skiffer-git submitted a review, later dismissed

2023-11-07 06:08 UTC, cubxxw approved these changes

2023-11-07 06:36 UTC, skiffer-git approved these changes

2023-11-07 06:37 UTC, merged