add webhooks
openimsdk/open-im-server pull request #1465
Opened 2023-11-23 04:36 UTC by AndrewZuo01

<br>

#### 🔍 What type of PR is this?

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

update webhooks

#### 🅰 Which issue(s) this PR fixes:

Fixes #

#### 📝 Special notes for your reviewer:

#### 🎯 Describe how to verify it

#### 📑 Additional documentation e.g., RFC, notion, Google docs, usage docs, etc.:

2023-11-23 06:33 UTC, AndrewZuo01 commented
I have read the CLA Document and I hereby sign the CLA

2023-11-23 06:54 UTC, cubxxw approved these changes

2023-11-29 02:13 UTC, cubxxw submitted a review, later dismissed
lgtm

2023-11-29 02:49 UTC, Bloomingg submitted a review, later dismissed

2023-11-29 06:42 UTC, FGadvancer approved these changes

2023-11-29 06:53 UTC, cubxxw approved these changes

2023-11-29 07:34 UTC, cubxxw requested changes

2023-11-29 07:34 UTC, cubxxw commented on deployments/templates/openim.yaml
> -    enable: ${CALLBACK_ENABLE}
I suggest using the export setting instead of hardcoding it, as it would be difficult to enable callback and conduct testing in a CICD environment with hardcoded values. It would be beneficial to set the environment variable's default value as false.

2023-11-29 08:02 UTC, cubxxw approved these changes
<img src="https://media4.giphy.com/media/s3VRPZLjcj5FAbMwlf/giphy.gif"/>

2023-11-29 08:02 UTC, cubxxw commented on scripts/install/environment.sh
>  def "CALLBACK_ENABLE" "true"          # 是否开启 Callback
here is false

2023-11-29 13:14 UTC, FGadvancer approved these changes

2023-11-30 02:10 UTC, skiffer-git approved these changes

2023-11-30 02:11 UTC, merged