add crud for general function user process, add pinFriend
openimsdk/open-im-server pull request #1532
Opened 2023-12-07 09:46 UTC by AndrewZuo01

<br>

#### 🔍 What type of PR is this?

#### 👀 What this PR does / why we need it:

- [x ] My pull request adheres to the code style of this project
- [x ] My code requires changes to the documentation
- [x ] I have updated the documentation as required
- [x ] All the tests have passed

add crud for general function user process. For example, add to favorite

#### 🅰 Which issue(s) this PR fixes:

Fixes #

#### 📝 Special notes for your reviewer:

#### 🎯 Describe how to verify it

#### 📑 Additional documentation e.g., RFC, notion, Google docs, usage docs, etc.:

2023-12-11 06:30 UTC, cubxxw requested changes

2023-12-11 06:30 UTC, cubxxw commented on internal/rpc/friend/friend.go
> +	//檢查是不是在好友列表裏
Why use Chinese comments?

2023-12-11 06:30 UTC, cubxxw commented on internal/api/route.go
> +		userRouterGroup.POST("/process_user_command_delete", ParseToken, u.ProcessUserCommandDelete)
+ [ ] add api code 
+ [ ] add api docs
+ [ ] add api aotu test (cicd)

2023-12-11 07:18 UTC, AndrewZuo01 commented on internal/rpc/friend/friend.go
> +	//檢查是不是在好友列表裏
because other comments are also Chinese

2023-12-12 15:45 UTC, cubxxw approved these changes

2023-12-12 15:48 UTC, cubxxw requested changes
CICD error

2023-12-13 01:54 UTC, cubxxw approved these changes

2023-12-15 09:18 UTC, AndrewZuo01 reviewed
please merge pin friend

2023-12-15 09:18 UTC, AndrewZuo01 commented on internal/api/route.go
> +		userRouterGroup.POST("/process_user_command_delete", ParseToken, u.ProcessUserCommandDelete)
already add api doc and test

2023-12-16 15:26 UTC, cubxxw approved these changes

2023-12-18 10:35 UTC, FGadvancer approved these changes

2023-12-18 10:38 UTC, cubxxw approved these changes

2023-12-18 10:38 UTC, cubxxw commented on go.mod
> +//	github.com/OpenIMSDK/protocol v0.0.34 => github.com/AndrewZuo01/protocol v0.0.0-20231218034338-b8d838e0b182
??
why?

2023-12-18 10:39 UTC, AndrewZuo01 commented on go.mod
> +//	github.com/OpenIMSDK/protocol v0.0.34 => github.com/AndrewZuo01/protocol v0.0.0-20231218034338-b8d838e0b182
for easy to modify

2023-12-18 10:40 UTC, merged