Groupmsg
openimsdk/open-im-server pull request #2548
Opened 2024-08-22 10:04 UTC by icey-yu

## 🅰 Please add the issue ID after "Fixes #"

Fixes #
Add enable history for new members.
Refactor enter member notification.

2024-08-22 10:41 UTC, FGadvancer approved these changes

2024-08-23 02:54 UTC, mo3et requested changes

2024-08-23 02:54 UTC, mo3et commented on internal/rpc/conversation/conversaion.go
> +	if err := c.conversationDatabase.UpdateUsersConversationField(ctx, req.OwnerUserID, req.ConversationID,
This method is update `conversation` collection. but Seq is save in `seq` collection in DB.

Need check.

@FGadvancer

2024-08-23 02:55 UTC, mo3et commented
@FGadvancer Need check update field to correct collection.

2024-08-23 09:34 UTC, mo3et approved these changes

2024-08-23 09:35 UTC, merged